### ISSUE TITLE
Poprawki wyglądu oraz funkcjonalności strony www

### ISSUE THREAD

**Issue by tmikuczewski** [tmikuczewski/issues-test-repo#1]
# W trakcie użytkowania znaleziono kilka miejsc portalu, które należy usprawnić/zmienić.

Poniżej znajduje się lista zagadnień, które został utworzone na potrzeby tego zadania. Wymagania do poszczególnych zagadnień zostały umieszczone w ramach danego zadania.

## 1. Design:
- [ ] Zmiana wyglądu profilu użytkownika (#2)
- [ ] Zmiana wyglądu formatki edycji bloga (#3)

## 2. Funkcjonalność:
- [ ] Zmiana mechanizmu dodawania zdjęć do posta (#4)
- [ ] Galeria zdjęć - kolejność wyświetlania (#5)

**Comment by tmikuczewski** [comment]
### Rozpoczęto prace nad daną grupą zagadnień.
